# If the plugin should check if the block under the seed is farmland before replanting.
CheckForFarmland: true

# Delay in ticks from when block is broken to replant.
# Might need to be 1 or above to prevent a small issue with McMMOs herbalism replant.
ReplantDelay: 1

# If the plugin should check the players inventory before creating a runnable (delayed task) for the required item. (It will also check before actually replanting either way.)
ExtraInventoryCheckForItem: true

# Call a BlockPlaceEvent after replanting. lets plugin like CoreProtect log that you replanted that seed, etc.
ShouldCallBlockPlaceEvent: true

# Use Player#updateInventory. Set to true if there is any problems with removing the seeds from inventory.
UpdatePlayerInventory: false

# If the player is required to hold one of the Materials in RequiredItemMaterials for it to replant.
RequireItem: true
# Valid materials: https://hub.spigotmc.org/javadocs/spigot/org/bukkit/Material.html
RequiredItemMaterials:
  - 'DIAMOND_HOE'
  - 'IRON_HOE'

# The default permission for replanting.
# All seeds will require this permission.
DefaultPermission: 'auto.replant'

Seeds:
  # Material of item to replant. Only valid materials are: CROPS, CARROT, POTATO, BEETROOT_BLOCK, NETHER_WARTS.
  # Don't want the plugin to replant one or more of the types? just remove it from the list.
  WHEAT:
    # How old the seed is when it gets replanted, 0 indicates that the seed was just planted.
    NewState: 0
    # Valid materials here: https://hub.spigotmc.org/javadocs/spigot/org/bukkit/Material.html
    RequiredItem: WHEAT_SEEDS
    # What block to check for if CheckForFarmland is true. Can be removed, will default to SOIL.
    RequiredBlock: FARMLAND
  CARROTS:
    NewState: 0
    RequiredItem: CARROT
  POTATOES:
    NewState: 0
    RequiredItem: POTATO
  BEETROOTS:
    NewState: 0
    RequiredItem: BEETROOT_SEEDS
  NETHER_WART:
    # Valid states for Nether warts: https://hub.spigotmc.org/javadocs/spigot/org/bukkit/NetherWartsState.html
    NewState: 0
    RequiredItem: NETHER_WART
    RequiredBlock: SOUL_SAND
    # Specific permission for this type. Can be added to all types of seeds. Only DefaultPermission is required if this is removed.
    Permission: 'auto.replant.nether'
    # Permission for not needing to have a seed in inventory, defaults to auto.replant.noseed if removed.
    NoSeedPermission: 'auto.replant.noseed.nether'

# Explains itself.
Messages:
  NoPermission: '&fUnknown command. Type "/help" for help.'
  Reload: '&aReloaded AutoReplant configuration.'
